# A reusable CI workflow that builds and tests a mdbook.
#
# This worklfow requires that the caller provide a `test-mdbook` task in their Makefile
# that builds the mdbook and runs any tests. This allows the same command that is used
# locally to be run in this workflow.
#
##
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: Apache-2.0
##

on:
  workflow_call:

jobs:
  mdbook:
    name: Build and Test Mdbook

    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout Repository ✅
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: 🛠️ Download Rust Tools 🛠️
        uses: OpenDevicePartnership/patina-devops/.github/actions/rust-tool-cache@main

      - name: 📖 Build and Test Book 📖
        run: |
          cargo make test-mdbook
